import { createApp } from 'vue'
import router from './router/index'
import { RadioGroup, Image as VanImage, Uploader, Picker, Radio, Switch, Badge, PickerGroup, Search, DatePicker, Cell, CellGroup, TimePicker, Checkbox, CheckboxGroup, Icon, Popup, Divider, Form, Field, NavBar, ActionSheet, FloatingBubble, Button, Calendar, Tabbar, TabbarItem, Grid, GridItem } from 'vant'
// 2. 引入组件样式
import 'vant/lib/index.css'
import App from './App.vue'
const app = createApp(App)
app.use(router)
app.use(Radio)
app.use(Uploader)
app.use(Picker)
app.use(Cell)
app.use(CellGroup)
app.use(VanImage)
app.use(Search)
app.use(ActionSheet)
app.use(Badge)
app.use(PickerGroup)
app.use(DatePicker)
app.use(TimePicker)
app.use(Checkbox)
app.use(CheckboxGroup)
app.use(Switch)
app.use(Divider)
app.use(Form)
app.use(Field)
app.use(Popup)
app.use(NavBar)
app.use(FloatingBubble)
app.use(Icon)
app.use(Button)
app.use(RadioGroup)
app.use(Calendar)
app.use(Tabbar)
app.use(TabbarItem)
app.use(Grid)
app.use(GridItem)
app.mount('#app')
// createApp(App).use(router).use(Radio).use(Button).use(RadioGroup).use(Calendar).mount('#app')
